# Generated by Django 5.0.2 on 2024-05-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yumingle', '0007_alter_rating_rating_alter_rating_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='User',
        ),
    ]
