# Generated by Django 5.0.2 on 2024-05-28 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yumingle', '0013_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
