# Generated by Django 5.0.2 on 2024-05-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yumingle', '0016_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_variety',
            field=models.CharField(default='veg', max_length=10),
        ),
    ]
